name = "luna-file-converter-worker"
main = "src/index.ts"
compatibility_date = "2026-02-22"

[vars]
BUCKET_PUBLIC_HOST = "luna-cdn.madebydanny.uk"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "luna" # your real R2 bucket name
preview_bucket_name = "luna" # usually same bucket for preview
